/* ADMIN */
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const CREATE_CLASS = 'CREATE_CLASS';
export const CREATE_SUBJECT = 'CREATE_SUBJECT';
export const GET_CLASSES = 'GET_CLASSES';
export const GET_SUBJECT = 'GET_SUBJECT';
export const FILTER_CLASS = 'FILTER_CLASS';
export const CLASS_ERROR = 'CLASS_ERROR';
export const CREATE_STUDENT = 'CREATE_STUDENT';
export const GET_STUDENTS = 'GET_STUDENTS';
export const UPDATE_STUDENT = 'UPDATE_STUDENT';
export const SET_CURRENT = 'SET_CURRENT';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';
export const FILTER_STUDENT = 'FILTER_STUDENT';
export const PROMOTE_STUDENT = 'PROMOTE_STUDENT';
export const STUDENT_ERROR = 'STUDENT_ERROR';
export const CREATE_RE_STUDENT = 'CREATE_RE_STUDENT';
export const RE_STUDENT_ERROR = 'RE_STUDENT_ERROR';
export const CREATE_STAFF = 'CREATE_STAFF';
export const GET_STAFF = 'GET_STAFF';
export const UPDATE_STAFF = 'UPDATE_STAFF';
export const FILTER_STAFF = 'FILTER_STAFF';
export const GET_STAFFNAME = 'GET_STAFFNAME';
export const STAFF_ERROR = 'STAFF_ERROR';
export const GET_PARENT = 'GET_PARENT';
export const FILTER_PARENT = 'FILTER_PARENT';
export const PARENT_ERROR = 'PARENT_ERROR';
export const CREATE_PAYMENT = 'CREATE_PAYMENT';
export const UPDATE_PAYMENT = 'UPDATE_PAYMENT';
export const GET_PAYMENT = 'GET_PAYMENT';
export const FILTER_PAYMENT = 'FILTER_PAYMENT';
export const PAYMENT_ERROR = 'PAYMENT_ERROR';
export const GET_DESCRIPTION = 'GET_DESCRIPTION';
export const CREATE_DESCRIPTION = 'CREATE_DESCRIPTION';
export const GET_REPORT = 'GET_REPORT';
export const CREATE_REPORT = 'CREATE_REPORT';
export const SET_REPORT_CURRENT = 'SET_REPORT_CURRENT';
export const DELETE_REPORT = 'DELETE_REPORT';
export const FILTER_REPORT = 'FILTER_REPORT';
export const REPORT_ERROR = 'REPORT_ERROR';
export const LOGOUT = 'LOGOUT';

// STAFF
export const STAFF_LOADED = 'STAFF_LOADED';
export const STAFF_SUCCESS = 'STAFF_SUCCESS';

// PARENT
export const PARENT_LOADED = 'PARENT_LOADED';
export const PARENT_SUCCESS = 'PARENT_SUCCESS';
export const GET_STUDENT_RESULT = 'GET_STUDENT_RESULT';
